### ISSUE TITLE
VLANS Page

### ISSUE THREAD

**Issue by tomas99batista** [Self-Service-Campus/ssc-webapp#114]
- Ver a questao de ao clicar no go-to ports o botao para retroceder devia ser para as vlans list, não para os racks. hint: o botao deve fazer retroceder para last page opened e não para URL fixo; ou entao filtrar de onde vem o pedido, se vem dos racks vai para racks, se vem das vlans vai para vlans (se bem q acho esta + complicada

@flaviagfigueiredo JS?

**Comment by tomas99batista** [comment]
https://stackoverflow.com/questions/8067510/onclick-javascript-to-make-browser-go-back-to-previous-page

```
<button onclick="goBack()">Go Back</button>

<script>
function goBack() {
  window.history.back();
}
</script>
```


`<input type=button value="Previous Page" onClick="javascript:history.go(-1);">`

**Comment by flaviagfigueiredo** [comment]
✔ Return funciona
