### ISSUE TITLE
Eliminar elementos da lista de port security da porta referente

### ISSUE THREAD

**Issue by tomas99batista** [Self-Service-Campus/ssc-webapp#67]
Lista de mac address q podem ser la ligados, tudo oq seja diferente nao se pode ligar. (ex: ao ligar um novo pc ao switch ele vai bloquear a porta, deveria dar para poder consultar a port security e eliminar as entradas q la estao)

**Comment by flaviagfigueiredo** [comment]
Adiciona e remove
Falta terminar a estética

**Comment by tomas99batista** [comment]
- Frontend está feito, já faz tudo
- Apenas falta conexão à API
- Comandos worker para poder:
  -- adicionar/remover mac address
  -- ligar/desligar port security
- API faltam adicionar os 4 comandos dentro do worker
- Falta fazer a ligação do frontend c/ o worker (JQuery)
