### ISSUE TITLE
Black List de Switches

### ISSUE THREAD

**Issue by tomas99batista** [Self-Service-Campus/ssc-webapp#82]
Implementar um sistema de Black List para os switches.

Pex: todos os switches que comecem por stic, dc (data-center), core, etc, não fazem sentido aparecer porque isto é feito para uso departamental, logo não devem ser mostrados para não causar poluição visual.

Deve funcionar com "regex": "DC" todas os switches iniciados por DC não devem ser displayed

Quem pode manusear a blacklist: Administrator

@tomas99batista para filtrar os que nao se querem. para permissoes de quem pode ou nao adicionar a black list. Also ver #80 porque esta blacklist vai também filtrar lá
@flaviagfigueiredo para design
@Diaj3 design + para os logs

**Comment by tomas99batista** [comment]
Questions:
- Na blacklist, o regex indica como os switches começam? que palavras é que os switches não podem conter? startswith or contains?

**Comment by tomas99batista** [comment]
Solved:
- Problema que deixava inserir a mesma regex e os mesmos switches múltiplas vezes

TODO:
- Endpoint para apagar uma BL

**Comment by tomas99batista** [comment]
DONE:
- Endpoint para apagar. Falta ver c o @Diaj3 q tipo de resposta é que ele quer.

TODO:
- Retornar para o frontend as BL agrupadas por regex. Pex. Qdo é adicionado novo switch este deve aparecer dentro do novo grupo (se existir).

**Comment by tomas99batista** [comment]
Added response ok 200 and 400 BR

TODO:
- Retornar para o frontend as BL agrupadas por regex. Pex. Qdo é adicionado novo switch este deve aparecer dentro do novo grupo (se existir).

**Comment by tomas99batista** [comment]
- Já estao agrupados por regex. Porem n é solução final, n é eficaz e está uma merda. Depois vejo isto.

A partida não há + issues da minha parte, qql coisa relata @flaviagfigueiredo

**Comment by tomas99batista** [comment]
Pelo sim pelo não é melhor restringir a API delete e a pagina de blacklist a adminstrators para não haver URL Violation.

**Comment by flaviagfigueiredo** [comment]
✔ Alteração do design da página.
✔ Listagem dos switches por regex.
✔ Implementação do botão de remoção do regex.
✖ Link da blacklist e da whitelist na sidebar

![blacklist](https://user-images.githubusercontent.com/40077535/99704279-0f94cf80-2a90-11eb-8dd0-9f1ead889606.png)

**Comment by tomas99batista** [comment]
link white e black list: check, issue closed, nice
