### ISSUE TITLE
WhiteList de Switches

### ISSUE THREAD

**Issue by tomas99batista** [Self-Service-Campus/ssc-webapp#83]
Whitelist para adicionar novos switches (pelo IP) porque podem não vir na API do Prime mas mesmo assim queremos na aplicação.

Nós ja tinhamos isto antes, pegar no codigo antigo, etc. Escusamos de andar a bater com a cabeça novamente

Permissões: Só Administradores podem adicionar a whitelist

Label URGENTE pq é fast de implementar

@tomas99batista permissoes
@flaviagfigueiredo design da page
@diogoandrade1999 worker
@Diaj3 logs

**Comment by tomas99batista** [comment]
DONE:
- Form add Switch to whitelist
- Whitelist model
- urls
- api method para apagar switch da whitelist
- view para dar retrieve das whitelists existentes e para gerar/receber form

PROBLEMAS:
- o Switch necessita de um IP, como falsifica-lo? Dormir e pensar nisso, amanha trago uma resposta

**Comment by tomas99batista** [comment]
TODO:
- Clean fields after post @flaviagfigueiredo 

@tomas99batista  - check add remove etc

**Comment by flaviagfigueiredo** [comment]
✔ Clean fields after post
✔ Clean fields on Blacklist tambem after post

**Comment by tomas99batista** [comment]
TODO: 
@tomas99batista - check & test add remove etc

**Comment by flaviagfigueiredo** [comment]
> TODO:
> @tomas99batista - check & test add remove etc
> 
> @Diaj3 - logs

@flaviagfigueiredo && @tomas99batista readd css

**Comment by tomas99batista** [comment]
- add e remove ja estao a funcionar de novo
- campos nao estao a ser apagados ainda, fuck

TODO: 
- add request to celery
- clean fields
- logs
